version: '2'
services:
  db:
    build: ./postgrdb
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    depends_on:
      - db
    networks:
      - mynetwork

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HOME: /opt/kafka
    depends_on:
      - zookeeper
    networks:
      - mynetwork

  app:
    build: ./kafka_listener
    environment:
      KAFKA_HOST: kafka
      TZ: Europe/Moscow
    depends_on:
      - kafka
      - db
    volumes:
      - .:/app
      - ./logs:/app/logs
    networks:
      - mynetwork
      

  create-topics:
    build:
      context: ./create_topics
      dockerfile: Dockerfile
    depends_on:
      - kafka
    volumes:
      - .:/app
      - ./logs:/app/logs
    networks:
      - mynetwork
    environment:
      TZ: Europe/Moscow

  mainapp:
    build: .
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      - kafka
      - db
      - create-topics
      - api2kafka
    networks:
      - mynetwork
    environment:
      TZ: Europe/Moscow

  api2kafka:
    build: ./api2kafka
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      - kafka
      - db
    networks:
      - mynetwork
    environment:
      TZ: Europe/Moscow

networks:
  mynetwork: {}
