version: '2'
services:
  db:
    build: ./postgrdb
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    depends_on:
      - db

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HOME: /opt/kafka
    depends_on:
      - zookeeper

  app:
    build: kafka_listener/
    environment:
      KAFKA_HOST: kafka
    depends_on:
      - kafka

  create_topic:
    build:
      context: .
      dockerfile: Dockerfile.create-topic
    depends_on: 
      - kafka

  mainapp:
    build: .
    volumes:
      - .:/app
    depends_on:
      - kafka
      - db

networks:
  mynetwork: